// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANqBq8h15Z2CWA496FkHgxV00f2P1wvWQ',
    appId: '1:25433461928:web:5a3251819d743814f45e9d',
    messagingSenderId: '25433461928',
    projectId: 'auti-vr',
    authDomain: 'auti-vr.firebaseapp.com',
    storageBucket: 'auti-vr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm8oLqaTgmKutnRjQlIsvAXryCXjFfs3I',
    appId: '1:25433461928:android:12a792603a678c32f45e9d',
    messagingSenderId: '25433461928',
    projectId: 'auti-vr',
    storageBucket: 'auti-vr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqXNC6vmw4wvxRhApyKDVPHlTFGVCY8-U',
    appId: '1:25433461928:ios:89e1abe5b9058d34f45e9d',
    messagingSenderId: '25433461928',
    projectId: 'auti-vr',
    storageBucket: 'auti-vr.appspot.com',
    iosBundleId: 'com.example.autiVr',
  );
}
